# Generated by Django 4.1.2 on 2022-10-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options_rename_date_created_post_createds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createds',
            new_name='created',
        ),
    ]
